name: "GitHub Action for Perl's Dist::Zilla"
description: 'Use Dist-Zilla on your repository codebase'
author: jonasbn
inputs:
  dzil-arguments:  # id of input
    description: 'Arguments for dzil'
    required: true
    default: 'help'
branding:
  color: red
  icon: zap
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.dzil-arguments }}
